from enum import Enum


class RealEstate(Enum):
    BTG_PACTUAL_LOGISTICA = "BTLG11"
    IRIDIUM = "IRDM11"
    MALLS_BRASIL_PLURAL = "MALL11"
    MAUA_CAPITAL = "MCCI11"
    TRX_REAL_ESTATE = "TRXF11"