from enum import Enum


class Stock(Enum):
    BRASILAGRO = "AGRO3"
    BANCO_DO_BRASIL = "BBAS3"
    BB_SEGURIDADE = "BBSE3"
    COPEL = "CPLE6"
    ENGIE_BRASIL = "EGIE3"
    MAHLE_METAL_LEVE = "LEVE3"
    PETROBRAS = "PETR4"
    TUPY = "TUPY3"
    VALE = "VALE3"
    BTG_PACTUAL_LOGISTICA = "BTLG11"
    IRIDIUM = "IRDM11"
    MALLS_BRASIL_PLURAL = "MALL11"
    MAUA_CAPITAL = "MCCI11"
    TRX_REAL_ESTATE = "TRXF11"